[package]
name = "creased_cube_to_step"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
opensubdiv-petite = { path = "../..", features = ["truck_integration"] }
truck-modeling = "0.6"
truck-stepio = "0.3"
glam = "0.29"
anyhow = "1.0"